server:
  port: 8081


## MongoDB数据库
#  spring.data.mongodb.uri=mongodb://127.0.0.1:27017/testd
#
#  # 设置了密码的MongoDB配置方式
#  # MongoDB服务器连接地址
#  spring.data.mongodb.host=127.0.0.1
#  # MongoDB服务器连接端口
#  spring.data.mongodb.port=27017
#  # MongoDB的验证数据库
#  #spring.data.mongodb.authentication-database=admin
#  # MongoDB数据库用户
#  #spring.data.mongodb.username=root
#  # MongoDB数据库密码
#  #spring.data.mongodb.password=123456
#  # 带连接的数据库
#  #spring.data.mongodb.database=testMongoDB
spring:
  data:
    mongodb:
      username: root
      password: root123
      host: 127.0.0.1
      port: 27017
      database: testd